export const homeObjOne = {
  id: 'howitworks',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'How it works',
  headline: 'Machine Learning and NLP',
  description: 'Get access to our exclusive app that allows you to incentivize knowledge sharing',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/svg-1.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'pricing',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Pricing',
  headline: 'Affordable',
  description: 'Get access to our exclusive app that allows you to do cool stuff',
  buttonLabel: 'Learn more',
  imgStart: false,
  img: require('../../images/svg-2.svg').default,
  alt: 'Phone',
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Join our team',
  headline: 'Creating an account is extremely easy',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/svg-3.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};